# Bienvenue {.unnumbered}

```{r}
#| echo: false

source("_common.R")
```

## Aperçu de l'initiative Countdown to 2030 {.unnumbered}

L'initiative Countdown to 2030 pour la santé des femmes, des enfants et des adolescents (The Countdown) est une collaboration mondiale impliquant des universitaires d'institutions nationales, régionales et internationales, des agences des Nations Unies, la Banque Mondiale et des organisations de la société civile. L'initiative suit les progrès en matière de santé et de nutrition reproductive, maternelle, néonatale, infantile et adolescente (RMNCAH+N), favorisant la promotion et la responsabilisation par une analyse rigoureuse des données.

**Les objectifs clés comprennent :**

-   Renforcer l'analyse et le suivi des données menés par les pays
-   Favoriser l'innovation et la génération de preuves grâce à la collaboration multinationale
-   Améliorer la mesure et le suivi à l'échelle mondiale
-   Améliorer la communication des politiques et des programmes

Pour en savoir plus sur l'initiative Countdown to 2030, visitez : [Le site web The Countdown](https://www.countdown2030.org/about)

## À propos du package R `cd2030.rmncah` {.unnumbered}

Le package R et l'application Shiny `cd2030.rmncah` ont été développés pour soutenir la génération de preuves et l'analyse des indicateurs RMNCAH.

**Les principales caractéristiques comprennent :**

-   Interface conviviale pour la gestion et l'analyse des données
-   Outils de visualisation et de résumé statistique
-   Génération automatisée de rapports

## Remerciements {.unnumbered}

The Countdown reconnaît et apprécie la contribution de l'individu suivant dans le développement des codes Stata qui constituent la base du package R et de l'application Shiny `cd2030.rmncah` :
