---
title: "Maternal Mortality"
format: html
---

## Maternal Mortality

### Rationale, Approach and implementation

**Rationale: Scientific basis for the analysis**

Maternal and perinatal mortality in health facilities are critical indicators of the quality of care (institutional mortality). Institutional maternal mortality is one of the key indicators proposed to monitor progress. Facility-based mortality statistics can also be a critical input into the estimation of population levels of mortality.

Reporting of maternal deaths, stillbirths, and early neonatal deaths (before discharge) may occur through the routine reporting system (DHIS2, aggregate or individual level) or be part of a maternal and perinatal death surveillance and response system (MPDSR).

Population mortality statistics (maternal mortality ratio, stillbirth rates, neonatal mortality rates) rely on household surveys and censuses, with major limitations, especially for maternal mortality and stillbirths. A promising development is the major increase in health facility deliveries observed in many countries.

Especially if coverage of births in health facilities is high (e.g., over 75%), the facility-based statistics will become a useful input into the estimation of population levels of mortality. The main challenge with mortality data from health facilities is under-reporting of deaths. Maternal deaths do not only occur during birth, but also in pregnancy and post-partum.

Reporting of stillbirth deaths requires well maintained maternity registers, but also cross-checks to the operation theatre registers for cases of Caesarean section. If that is not the case, deaths may not be recorded in the maternity register, and not reported into the national system. In addition, maternal deaths occurring in other hospital wards are more likely to be missed, such as deaths associated with abortion, or post-discharge due to sepsis and other causes. Neonatal deaths after discharge, which is often within 24 hours, are also more likely to be missed.

A critical step is a systematic assessment of data quality issues, which forms the basis for, if possible, adjustments, and more importantly should guide efforts to improve reporting quality.
