---
title: "Sub-national coverage"
format: html
---

## Sub-national Coverage

### Rationale, Approach and implementation

**Rationale: Scientific basis for the analysis**

Sub-national analysis of health intervention coverage is essential for advancing universal health coverage (UHC), which aims to ensure equitable access to quality health services for all populations. National averages often mask critical disparities that exist across regions, districts, or population subgroups.

Monitoring subnational data helps identify geographical areas where coverage is low, signaling potential inequities in health service access and prompting targeted interventions. This is particularly important for drawing attention to populations who are left behind and ensuring resources are directed where they are most needed.

**Approach: Description of analytical steps**

The focus should be on assessing the extent to which the country programs have succeeded in reducing the inequalities between regions/provinces and between districts, and the extent to which districts have reached a coverage target. Three global targets for coverage indicators are of particular interest:

-   ANC4: 80% of districts have at least 70% coverage (EPMM/ENAP)

-   SBA or institutional delivery: 80% of districts have at least 80% coverage (EPMM/ENAP)

-   Penta3/DTP3: at least 80% coverage in every district or equivalent administrative unit with three doses of diphtheria-tetanus-pertussis containing vaccines (DTP -- or pentavalent vaccine).

The regional and district analyses should use the best performing denominator for the coverage computations, as decided from the analysis in section 2 on denominators. There will be more "noise" in the subnational data with improbably high or low coverage rates, compared to the national analyses, and more so in the district analyses than in the regional (admin1) analyses. This is because district analyses are affected by small numbers (more fluctuations which may be random or due to data quality issues) and by the health service utilization patterns by women and children. For instance, a municipal district may get more deliveries than an adjacent rural district because of the location of the hospitals in the municipal district.

The key statistical measures for subnational inequalities are:

-   MADM: median absolute distance from the median. This measure gives an indication on whether the country has been successful in reducing inequalities between subnational units.

-   Percent of subnational units with coverage above a specific target or threshold: this indicator provides information on the extent to which a country has been successful in reaching universal coverage at the subnational level.

*Summary of district and regional performance*

Progress towards international and national targets can be measured by computing the percentage of regions and districts that have achieved these targets. The goal is for all regions and districts to have met the target. Higher percentages mean less inequality.

**Implementation: Conducting analysis in the Shiny App**

This would be done in the Sub-national analyses section in the app.

(insert screenshot)

Outputs will include Percent of regions and percent of districts that have achieved specific targets for ANC4, institutional deliveries and penta3 vaccination as shown below. (insert screenshot)

Further analyses may also include plotting of regional or district results by year, with the median absolute distance from the median (MADM, see screenshot below), as the summary measure to assess if inequalities have reduced.

(insert image)

To summarize the coverage situation according to the health facility statistics for 2024 can be done for the regional level and shown on a map. A composite coverage index is computed as an average in seven mother and child health indicators: **ANC4**, **institutional live birth coverage**, **SBA**, **IPT2**, **postnatal care**, **pentavalent vaccine 3rd dosage** and **measles 1** vaccination coverage. Equal weight is given to all indicators.

**Sub-national statistical summaries**

The aim is to produce a one-pager for each admin1 unit (generally region, province or county) that contains the regional information as well as a summary of the districts within the region. We refer to this as a regional subnational statistical summary.

The following components are included:

-   Summary of key demographic information for the region and the districts: table with expected number of births in 2024 according to the DHIS2 projections and according to the preferred denominators derived from the health facility data (based on ANC1 for live births, and on penta1 for immunization indicators).

-   Line graphs with the trend in coverage of institutional deliveries and penta3 vaccination that include the best estimates for 2020-2024 based on the health facility data, as well as the estimates from the most recent surveys (from 2015) for the same indicators (with confidence intervals if possible).

-   Bar graphs that compare the 2024 coverage situation in the region compared to all other regions, and puts the region into the lowest, middle or upper third of regions in terms of coverage. This is done for both institutional deliveries and penta3 vaccination.

-   Table that summarizes the coverage for institutional deliveries and penta3 vaccination in 2024 by district.

-   Other indicators can be used as prioritized by the country (e.g., ANC4, measles1).

(insert screenshot)
