name: Render and Publish

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install required R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            knitr
            kableExtra
            here
            github::ropensci-review-tools/babelquarto@a485fea

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Book with babelquarto
        run: Rscript -e 'babelquarto::render_book()'
        
      - name: Archive book render
        uses: actions/upload-artifact@v4
        with:
          name: book_render
          path: _book/

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
